import { useMemo, useState } from 'react';
import type { SoundClip, SoundGenerator, SoundLibraryItem, SoundProject, SoundTrack } from '@chatter/shared';

export type FoleyTool = 'SOUNDS' | 'RECORD' | 'MAKE' | 'ARRANGE' | 'SHAPE' | 'MIX' | 'FINISH';
export interface FoleyCanvasProps {
  project: SoundProject; edit: (recipe: (draft: SoundProject) => void) => void; busy: boolean;
  selectedId?: string; onSelect: (id: string) => void; playhead: number; onSeek: (at: number) => void;
  items?: SoundLibraryItem[]; trackId?: string; onTrackSelect?: (id: string) => void;
}
export const soundClipLength = (clip: SoundClip) => (clip.sourceOut - clip.sourceIn) / clip.rate * clip.repeats;
const onceLength = (clip: SoundClip) => (clip.sourceOut - clip.sourceIn) / clip.rate;
const bounded = (value: number, low: number, high: number) => Math.max(low, Math.min(Math.max(low, high), value));
const clock = (value: number) => `${Number(value.toFixed(2))}s`;
const gainLabel = (value: number) => `${value > 0 ? '+' : ''}${Number(value.toFixed(1))} dB`;
function selectedTrack(props: FoleyCanvasProps) { const clip = props.project.clips.find(row => row.id === props.selectedId); return props.project.tracks.find(row => row.id === (clip?.trackId ?? props.trackId)) ?? props.project.tracks[0]; }
function exact(label: string, value: number, min: number, max: number, step: number, onChange: (value: number) => void) {
  return <label className="foley-control">{label}<input type="number" aria-label={label} value={Number(value.toFixed(4))} min={min} max={Math.max(min, max)} step={step} onChange={event => { if (event.target.value !== '' && Number.isFinite(event.target.valueAsNumber)) onChange(bounded(event.target.valueAsNumber, min, max)); }} /></label>;
}
function slider(label: string, value: number, min: number, max: number, step: number, onChange: (value: number) => void, display: string, ends?: [string, string]) {
  return <label className="foley-control foley-slider"><span>{label}<output className="foley-control-value">{display}</output></span><input type="range" aria-label={label} aria-valuetext={display} value={value} min={min} max={Math.max(min, max)} step={step} onChange={event => onChange(bounded(event.target.valueAsNumber, min, max))} />{ends && <span className="foley-control-ends" aria-hidden="true"><span>{ends[0]}</span><span>{ends[1]}</span></span>}</label>;
}

/** Library peaks are measured audio; generated clips show their editable amplitude envelope. */
function ClipArtwork({ clip, item }: { clip: SoundClip; item?: SoundLibraryItem }) {
  const path = useMemo(() => {
    const bars = 100; const recipe = clip.generator; let shape = '';
    for (let i = 0; i < bars; i++) {
      const progress = (i + 0.5) / bars; const position = (progress * clip.repeats) % 1;
      const sourceTime = clip.sourceIn + position * (clip.sourceOut - clip.sourceIn);
      let amplitude = 0;
      if (recipe) {
        amplitude = Math.min(1, sourceTime / Math.max(.003, recipe.attack)) * Math.min(1, (recipe.duration - sourceTime) / Math.max(.003, recipe.release));
        if (recipe.pulseHz) amplitude *= Math.pow(.5 + .5 * Math.cos(sourceTime * Math.PI * 2 * recipe.pulseHz), 3);
        amplitude *= .7;
      } else if (item?.peaks.length && item.duration > 0) amplitude = item.peaks[Math.min(item.peaks.length - 1, Math.floor(sourceTime / item.duration * item.peaks.length))] ?? 0;
      const local = position * onceLength(clip);
      amplitude *= (clip.fadeIn ? Math.min(1, local / clip.fadeIn) : 1) * (clip.fadeOut ? Math.min(1, (onceLength(clip) - local) / clip.fadeOut) : 1);
      const height = Math.max(.8, Math.min(1, amplitude) * 18);
      shape += `M${i + .5} ${20 - height}v${height * 2}`;
    }
    return shape;
  }, [clip.generator, clip.sourceIn, clip.sourceOut, clip.rate, clip.repeats, clip.fadeIn, clip.fadeOut, item]);
  return <svg className="foley-region-waveform" viewBox="0 0 100 40" preserveAspectRatio="none" role="img" aria-label={clip.generator ? 'Generated sound envelope' : item?.peaks.length ? 'Recorded sound waveform' : 'Waveform unavailable'}><path d={path} fill="none" stroke="currentColor" strokeWidth=".65" /></svg>;
}

export function FoleyCanvas(props: FoleyCanvasProps) {
  const { project, edit, busy, selectedId, onSelect, playhead, onSeek, items = [], onTrackSelect } = props;
  const track = selectedTrack(props); const selected = project.clips.find(clip => clip.id === selectedId);
  const length = Math.min(300, Math.max(5, project.exportEnd, ...project.clips.map(row => row.start + soundClipLength(row))));
  const unit = project.snap === 'BEATS' ? 60 / project.bpm : project.snap === 'SECONDS' ? .1 : .001;
  const move = (id: string, start: number, trackId?: string) => edit(draft => { const clip = draft.clips.find(row => row.id === id); if (clip) { clip.start = bounded(start, 0, 299); if (trackId) clip.trackId = trackId; } });
  const position = (event: React.MouseEvent | React.DragEvent) => { const rect = event.currentTarget.getBoundingClientRect(); return bounded((event.clientX - rect.left) / Math.max(1, rect.width) * length, 0, 300); };
  return <section className="foley-canvas foley-panel" aria-label="Sound canvas"><header className="foley-canvas-header"><div><span className="foley-eyebrow">YOUR SOUND CANVAS</span><h2>{project.name || 'Untitled cue'}</h2></div><span className="foley-canvas-selection">{selected ? selected.name : 'Pick a sound to shape it'}</span><button disabled={busy || project.tracks.length >= 8} onClick={() => { const id = crypto.randomUUID(); edit(draft => { draft.tracks.push({ id, name: `Layer ${draft.tracks.length + 1}`, gainDb: 0, pan: 0, muted: false, filterHz: 20000, delaySec: 0, delayMix: 0, reverbMix: 0 }); }); onSelect(''); onTrackSelect?.(id); }}>+ Add layer</button></header>
    <fieldset disabled={busy}><div className="foley-ruler" aria-label="Timeline seconds">{Array.from({ length: 6 }, (_, index) => <span key={index}>{clock(length * index / 5)}</span>)}</div>
      <div className="foley-timeline">{project.tracks.map(row => <div key={row.id} className={`foley-track ${row.muted ? 'is-muted' : ''}`}><button className={track?.id === row.id ? 'is-selected' : ''} aria-pressed={track?.id === row.id} aria-label={`Select ${row.name}${row.muted ? ', muted' : ''}`} onClick={() => { onSelect(''); onTrackSelect?.(row.id); }}><span>{row.name}</span>{row.muted && <small>Muted</small>}</button>
        <div className="foley-lane" onClick={event => { if (event.target !== event.currentTarget || busy) return; onSeek(position(event)); onSelect(''); onTrackSelect?.(row.id); }} onDragOver={event => { if (event.dataTransfer.types.includes('application/x-foley-clip')) event.preventDefault(); }} onDrop={event => { const id = event.dataTransfer.getData('application/x-foley-clip'); if (!id || busy) return; event.preventDefault(); event.stopPropagation(); move(id, Math.round(position(event) / unit) * unit, row.id); onSelect(id); }}>
          {project.clips.filter(clip => clip.trackId === row.id).map(clip => <button key={clip.id} draggable={!busy} onDragStart={event => event.dataTransfer.setData('application/x-foley-clip', clip.id)} className={`foley-region ${selectedId === clip.id ? 'is-selected' : ''} ${clip.generator ? 'is-generated' : 'is-recorded'}`} style={{ left: `${clip.start / length * 100}%`, width: `${Math.max(.8, Math.min(soundClipLength(clip), Math.max(0, length - clip.start)) / length * 100)}%` }} aria-pressed={selectedId === clip.id} aria-label={`${clip.name}, ${clock(clip.start)}, ${clock(soundClipLength(clip))}. Select to edit; arrow keys move.`} onClick={() => onSelect(clip.id)} onKeyDown={event => { if (!busy && (event.key === 'ArrowLeft' || event.key === 'ArrowRight')) { event.preventDefault(); move(clip.id, clip.start + (event.key === 'ArrowLeft' ? -1 : 1) * (event.shiftKey ? .01 : unit)); } }}><span className="foley-region-name">{clip.name}</span><ClipArtwork clip={clip} item={items.find(item => item.id === clip.libraryItemId) ?? items.find(item => item.assetId === clip.assetId)} /><small className="foley-region-duration">{clock(soundClipLength(clip))}{clip.repeats > 1 ? ` · ×${clip.repeats}` : ''}</small></button>)}
          <span className="foley-export-window" aria-hidden="true" style={{ left: `${project.exportStart / length * 100}%`, width: `${(project.exportEnd - project.exportStart) / length * 100}%` }} /><span className="foley-playhead" style={{ left: `${bounded(playhead / length * 100, 0, 100)}%` }} aria-hidden="true" />
        </div></div>)}</div>
      {!project.clips.length && <div className="foley-canvas-empty"><strong>A little sound goes a long way.</strong><p>Pick a starter, bring a recording, or make something from scratch.</p></div>}
      <div className="foley-canvas-foot"><span className="foley-range-note">Keep {clock(project.exportStart)} – {clock(project.exportEnd)}{project.loop ? ' · loop' : ' + effect tails'}</span>{slider('Listening position', playhead, 0, length, .01, onSeek, clock(playhead), ['Start', 'End'])}<p className="foley-hint">Drag to arrange. Select to shape. Arrow keys nudge a selected sound.</p></div>
    </fieldset></section>;
}

export function FoleyToolOptions(props: FoleyCanvasProps & { tool: FoleyTool }) {
  const { project, edit, busy, selectedId, onSelect, playhead, onSeek, items = [], tool } = props;
  const clip = project.clips.find(row => row.id === selectedId); const track = selectedTrack(props);
  const updateClip = (patch: Partial<SoundClip>) => { if (clip) edit(draft => { const next = draft.clips.find(row => row.id === clip.id)!; Object.assign(next, patch); const duration = onceLength(next); next.fadeIn = bounded(next.fadeIn, 0, duration); next.fadeOut = bounded(next.fadeOut, 0, duration); }); };
  const updateTrack = (patch: Partial<SoundTrack>) => { if (track) edit(draft => { Object.assign(draft.tracks.find(row => row.id === track.id)!, patch); }); };
  const range = (patch: Partial<Pick<SoundProject, 'exportStart' | 'exportEnd' | 'loop' | 'loopCrossfade'>>) => edit(draft => { Object.assign(draft, patch); if (draft.loopCrossfade !== undefined) draft.loopCrossfade = Math.min(draft.loopCrossfade, (draft.exportEnd - draft.exportStart) / 2); });
  const sourceDuration = clip?.generator?.duration ?? items.find(item => item.id === clip?.libraryItemId)?.duration ?? items.find(item => item.assetId === clip?.assetId)?.duration ?? clip?.sourceOut ?? 300;
  const canSplit = clip && clip.repeats === 1 && playhead > clip.start + .01 && playhead < clip.start + onceLength(clip) - .01 && project.clips.length < 64;
  function split() {
    if (!clip || !canSplit) return;
    edit(draft => { const left = draft.clips.find(row => row.id === clip.id)!; const source = left.sourceIn + (playhead - left.start) * left.rate;
      const right = { ...left, id: crypto.randomUUID(), name: `${left.name} · split`, start: playhead, sourceIn: source, fadeIn: 0 };
      right.fadeOut = Math.min(right.fadeOut, onceLength(right)); left.sourceOut = source; left.fadeOut = 0; left.fadeIn = Math.min(left.fadeIn, onceLength(left)); draft.clips.push(right);
    });
  }
  const choose = <div className="foley-tool-empty"><strong>Pick a sound on your canvas.</strong><p>Its controls will appear here.</p></div>;
  return <section className={`foley-tool-options foley-options-${tool.toLowerCase()}`} aria-label={`${tool.toLowerCase()} options`}><fieldset disabled={busy}>
    {tool === 'ARRANGE' && <><p className="foley-tool-hint">Put each sound where it belongs.</p><label className="foley-control">Snap into place<select aria-label="Timeline snapping" value={project.snap} onChange={event => edit(draft => { draft.snap = event.target.value as SoundProject['snap']; })}><option value="SECONDS">Small steps</option><option value="BEATS">On the beat</option><option value="OFF">Move freely</option></select></label>{project.snap === 'BEATS' && exact('Beats per minute', project.bpm, 40, 240, 1, value => edit(draft => { draft.bpm = value; }))}
      {clip ? <><h3>{clip.name}</h3><label className="foley-control">Layer<select aria-label="Clip layer" value={clip.trackId} onChange={event => updateClip({ trackId: event.target.value })}>{project.tracks.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{slider('Place in cue', clip.start, 0, Math.max(project.exportEnd, clip.start, 5), .01, value => updateClip({ start: Math.min(299, value) }), clock(clip.start))}{exact('Play this many times', clip.repeats, 1, 64, 1, value => updateClip({ repeats: Math.floor(value) }))}
        <div className="foley-actions"><button disabled={project.clips.length >= 64} onClick={() => { const id = crypto.randomUUID(); edit(draft => { draft.clips.push({ ...structuredClone(clip), id, start: Math.min(299, clip.start + soundClipLength(clip)) }); }); onSelect(id); }}>Make a copy</button><button disabled={!canSplit} onClick={split}>Split here</button><button onClick={() => { edit(draft => { draft.clips = draft.clips.filter(row => row.id !== clip.id); }); onSelect(''); }}>Remove sound</button></div><details className="foley-precise"><summary>Exact placement & name</summary><label className="foley-control">Sound name<input aria-label="Clip name" value={clip.name} maxLength={200} onChange={event => updateClip({ name: event.target.value })} /></label>{exact('Position (seconds)', clip.start, 0, 299, .01, value => updateClip({ start: value }))}{exact('Playhead (seconds)', playhead, 0, 300, .01, onSeek)}</details></> : choose}</>}
    {tool === 'SHAPE' && (clip ? <><h3>{clip.name}</h3><p className="foley-tool-hint">A softer entrance. A quicker exit. Make it feel right.</p>{slider('Volume', clip.gainDb, -60, 12, .5, gainDb => updateClip({ gainDb }), gainLabel(clip.gainDb), ['Quiet', 'Loud'])}{slider('Soft start', clip.fadeIn, 0, onceLength(clip), .01, fadeIn => updateClip({ fadeIn }), clock(clip.fadeIn), ['Immediate', 'Gentle'])}{slider('Soft finish', clip.fadeOut, 0, onceLength(clip), .01, fadeOut => updateClip({ fadeOut }), clock(clip.fadeOut), ['Immediate', 'Gentle'])}{slider('Speed', clip.rate, .25, 4, .05, rate => updateClip({ rate }), `${Number(clip.rate.toFixed(2))}×`, ['Slower + lower', 'Faster + higher'])}<details className="foley-precise"><summary>Trim & exact values</summary><p>Keep just the part you want. Speed changes pitch too.</p>{exact('Source in', clip.sourceIn, 0, clip.sourceOut - .01, .01, sourceIn => updateClip({ sourceIn }))}{exact('Source out', clip.sourceOut, clip.sourceIn + .01, sourceDuration, .01, sourceOut => updateClip({ sourceOut }))}{exact('Clip volume (dB)', clip.gainDb, -60, 12, .1, gainDb => updateClip({ gainDb }))}{exact('Fade in (seconds)', clip.fadeIn, 0, onceLength(clip), .01, fadeIn => updateClip({ fadeIn }))}{exact('Fade out (seconds)', clip.fadeOut, 0, onceLength(clip), .01, fadeOut => updateClip({ fadeOut }))}{exact('Speed and pitch', clip.rate, .25, 4, .01, rate => updateClip({ rate }))}</details></> : choose)}
    {tool === 'MAKE' && (clip?.generator ? <><h3>{clip.name}</h3><GeneratorControls recipe={clip.generator} onChange={generator => updateClip({ generator, sourceIn: 0, sourceOut: generator.duration })} /></> : <div className="foley-tool-empty"><strong>Start with a little spark.</strong><p>Choose a made sound from your starters to explore its pitch, texture and movement.</p></div>)}
    {tool === 'MIX' && track && <><h3>{track.name}</h3><p className="foley-tool-hint">Give this layer its own place and space.</p>{slider('Layer volume', track.gainDb, -60, 12, .5, gainDb => updateTrack({ gainDb }), gainLabel(track.gainDb), ['Quiet', 'Loud'])}{slider('Left ↔ right', track.pan, -1, 1, .05, pan => updateTrack({ pan }), track.pan === 0 ? 'Center' : `${Math.round(Math.abs(track.pan) * 100)}% ${track.pan < 0 ? 'left' : 'right'}`, ['Left', 'Right'])}{slider('Brightness', Math.log2(track.filterHz), Math.log2(20), Math.log2(24000), .02, value => updateTrack({ filterHz: Math.round(2 ** value) }), `${Math.round(track.filterHz)} Hz`, ['Warm', 'Bright'])}{slider('Echo', track.delayMix, 0, 1, .05, delayMix => updateTrack({ delayMix, ...(delayMix > 0 && track.delaySec === 0 ? { delaySec: .25 } : {}) }), `${Math.round(track.delayMix * 100)}%`, ['Dry', 'Repeating'])}{track.delayMix > 0 && slider('Echo spacing', track.delaySec, .01, 2, .01, delaySec => updateTrack({ delaySec }), clock(track.delaySec), ['Close', 'Far apart'])}{slider('Room', track.reverbMix, 0, 1, .05, reverbMix => updateTrack({ reverbMix }), `${Math.round(track.reverbMix * 100)}%`, ['Dry', 'Spacious'])}<label className="foley-toggle"><input type="checkbox" checked={track.muted} onChange={event => updateTrack({ muted: event.target.checked })} />Mute this layer</label><details className="foley-precise"><summary>Layer name & exact mix</summary><label className="foley-control">Layer name<input aria-label="Layer name" value={track.name} maxLength={100} onChange={event => updateTrack({ name: event.target.value })} /></label>{exact('Layer volume (dB)', track.gainDb, -60, 12, .1, gainDb => updateTrack({ gainDb }))}{exact('Pan', track.pan, -1, 1, .01, pan => updateTrack({ pan }))}{exact('Low-pass filter (Hz)', track.filterHz, 20, 24000, 1, filterHz => updateTrack({ filterHz }))}{exact('Echo delay (seconds)', track.delaySec, 0, 2, .01, delaySec => updateTrack({ delaySec }))}{exact('Echo amount', track.delayMix, 0, 1, .01, delayMix => updateTrack({ delayMix }))}{exact('Reverb amount', track.reverbMix, 0, 1, .01, reverbMix => updateTrack({ reverbMix }))}</details></>}
    {tool === 'FINISH' && <><p className="foley-tool-hint">Choose the piece you want to keep.</p><button onClick={() => range({ exportEnd: Math.min(300, Math.max(project.exportStart + .01, ...project.clips.map(row => row.start + soundClipLength(row)))) })}>Fit to all sounds</button><div className="foley-fields">{exact('Start at (seconds)', project.exportStart, 0, project.exportEnd - .01, .01, exportStart => range({ exportStart }))}{exact('End at (seconds)', project.exportEnd, project.exportStart + .01, 300, .01, exportEnd => range({ exportEnd }))}</div><label className="foley-toggle"><input type="checkbox" checked={project.loop} onChange={event => range({ loop: event.target.checked })} />Make a loop</label>{project.loop ? <>{slider('Smooth the join', project.loopCrossfade ?? Math.min(.02, (project.exportEnd - project.exportStart) / 2), 0, Math.min(2, (project.exportEnd - project.exportStart) / 2), .01, loopCrossfade => range({ loopCrossfade }), clock(project.loopCrossfade ?? .02), ['Tight', 'Blended'])}<p className="foley-hint">The end overlaps the beginning. Your saved loop is shorter by this overlap.</p></> : <p className="foley-hint">Echoes and room sound keep their natural finish in the saved cue.</p>}</>}
  </fieldset></section>;
}

export function GeneratorControls({ recipe, onChange }: { recipe: SoundGenerator; onChange: (next: SoundGenerator) => void }) {
  const change = (patch: Partial<SoundGenerator>) => { const next = { ...recipe, ...patch }; next.attack = Math.min(next.attack, next.duration); next.release = Math.min(next.release, next.duration); onChange(next); };
  const pitch = (label: string, key: 'frequency' | 'endFrequency') => slider(label, Math.log2(recipe[key]), Math.log2(20), Math.log2(20000), .02, value => change({ [key]: Math.round(2 ** value), ...(recipe.kind === 'NOISE' ? { color: 'LOW' as const } : {}) }), `${Math.round(recipe[key])} Hz`, recipe.kind === 'TONE' ? ['Low', 'High'] : ['Soft', 'Bright']);
  return <div className="foley-generator-controls"><label className="foley-control">Start with<select aria-label="Sound type" value={recipe.kind} onChange={event => change({ kind: event.target.value as SoundGenerator['kind'] })}><option value="NOISE">Air & texture</option><option value="TONE">A clear tone</option></select></label>{slider('Length', recipe.duration, .05, Math.max(30, recipe.duration), .05, duration => change({ duration }), clock(recipe.duration), ['A moment', 'A while'])}{pitch(recipe.kind === 'TONE' ? 'Starting pitch' : 'Starting brightness', 'frequency')}{pitch(recipe.kind === 'TONE' ? 'Ending pitch' : 'Ending brightness', 'endFrequency')}{slider('Ease in', recipe.attack, 0, recipe.duration, .01, attack => change({ attack }), clock(recipe.attack), ['Quick', 'Gentle'])}{slider('Ease out', recipe.release, 0, recipe.duration, .01, release => change({ release }), clock(recipe.release), ['Quick', 'Gentle'])}{slider('Pulse', recipe.pulseHz, 0, Math.max(30, recipe.pulseHz), .1, pulseHz => change({ pulseHz }), recipe.pulseHz ? `${Number(recipe.pulseHz.toFixed(1))} / sec` : 'Steady', ['Steady', 'Flutter'])}{recipe.kind === 'NOISE' && <label className="foley-control">Texture<select aria-label="Noise color" value={recipe.color} onChange={event => change({ color: event.target.value as SoundGenerator['color'] })}><option value="WHITE">Bright air</option><option value="LOW">Soft air</option></select></label>}{recipe.kind === 'NOISE' && <button onClick={() => change({ seed: Math.floor(Math.random() * 0x7fffffff) })}>Try another texture</button>}<details className="foley-precise"><summary>Exact sound recipe</summary>{exact('Duration (seconds)', recipe.duration, .01, 300, .01, duration => change({ duration }))}{exact('Starting frequency (Hz)', recipe.frequency, 20, 20000, 1, frequency => change({ frequency }))}{exact('Ending frequency (Hz)', recipe.endFrequency, 20, 20000, 1, endFrequency => change({ endFrequency }))}{exact('Attack (seconds)', recipe.attack, 0, recipe.duration, .01, attack => change({ attack }))}{exact('Release (seconds)', recipe.release, 0, recipe.duration, .01, release => change({ release }))}{exact('Pulses per second', recipe.pulseHz, 0, 40, .1, pulseHz => change({ pulseHz }))}{exact('Variation seed', recipe.seed, 0, 0xffffffff, 1, seed => change({ seed: Math.floor(seed) }))}</details></div>;
}

/** Compatibility for existing callers; the workspace can mount canvas and options separately. */
export function FoleyArrangement(props: FoleyCanvasProps) {
  const [trackId, setTrackId] = useState(props.project.tracks[0]?.id); const shared = { ...props, trackId: props.trackId ?? trackId, onTrackSelect: props.onTrackSelect ?? setTrackId };
  return <><FoleyCanvas {...shared} /><FoleyToolOptions {...shared} tool={props.selectedId ? 'SHAPE' : 'ARRANGE'} /></>;
}
