import { useState } from 'react';
import { stockSounds, stockSoundFamilies, type StockSound } from '../audio/stock-sounds.js';
import { ControlIcon } from '../components/ControlIcon.js';
import { SoundWaveform } from './FoleyLibrary.js';

export function FoleyStockSounds({ busy, onListen, onAdd }: { busy: boolean; onListen: (sound: StockSound) => void; onAdd: (sound: StockSound) => void }) {
  const [family, setFamily] = useState('Transitions'); const [query, setQuery] = useState('');
  const shown = stockSounds.filter(sound => (!query ? sound.category === family : `${sound.name} ${sound.description} ${sound.category} ${sound.attribution.creator}`.toLowerCase().includes(query.toLowerCase())));
  return <section className="foley-stock-sounds" aria-label="Included sound library"><p className="foley-stock-intro">Recorded sounds and finished cues, ready to use.</p><label>Find a sound<input type="search" aria-label="Search included sounds" placeholder="Rain, footsteps, whoosh…" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="foley-sound-families" aria-label="Sound families">{stockSoundFamilies.map(name => <button key={name} aria-pressed={!query && family === name} onClick={() => { setFamily(name); setQuery(''); }}>{name}</button>)}</div><div className="foley-sound-list">{shown.map(sound => <article key={sound.id} className="foley-sound-card"><header><strong>{sound.name}</strong><small>{sound.duration < .1 ? '<0.1' : sound.duration.toFixed(1)}s</small></header><SoundWaveform peaks={sound.peaks} /><p>{sound.description}</p><div className="foley-actions"><button disabled={busy} aria-label={`Listen to ${sound.name}`} onClick={() => onListen(sound)}><ControlIcon kind="play" />Listen</button><button disabled={busy} aria-label={`Add ${sound.name} to cue`} onClick={() => onAdd(sound)}>Add to cue</button></div><details className="foley-sound-more"><summary>Source & sound details</summary><p>{sound.attribution.creator} · {sound.attribution.license}<br />{sound.sampleRate.toLocaleString()} Hz · {sound.bits}-bit · {sound.channels === 1 ? 'Mono' : 'Stereo'} WAV</p><p><a href={sound.attribution.sourceUrl} target="_blank" rel="noreferrer">Original sound & license</a></p><p>{sound.attribution.notes}</p></details></article>)}</div>{!shown.length && <p>No included sounds match. Try another word or import your own.</p>}<p className="foley-hint">{stockSounds.length} sounds · Source credits travel with your project. Audio loads when you choose it.</p></section>;
}
