import { useEffect, useState } from 'react';
import type { Asset, SoundCollection, SoundLibraryItem, SoundRevision } from '@chatter/shared';
import { SoundCreditFields } from './FoleyImport.js';

export function SoundWaveform({ peaks }: { peaks: number[] }) {
  const values = peaks.length ? peaks : [0];
  return <svg className="foley-waveform" viewBox="0 0 360 48" preserveAspectRatio="none" aria-label={peaks.length ? 'Sound waveform' : 'Waveform not prepared'} role="img"><path d="M0 24H360" stroke="currentColor" opacity=".2" />{values.map((peak, index) => <path key={index} d={`M${index / values.length * 360} ${24 - Math.max(1, Math.min(1, peak) * 23)}v${Math.max(2, Math.min(1, peak) * 46)}`} stroke="currentColor" strokeWidth={Math.max(.7, 300 / values.length)} />)}</svg>;
}

export function FoleyLibrary({ items, assets, collections, revisions, busy, onAudition, onAdd, onUse, onEditSource, onUpdate, onCreateCollection }: {
  items: SoundLibraryItem[]; assets: Asset[]; collections: SoundCollection[]; revisions: SoundRevision[]; busy: boolean;
  onAudition: (item: SoundLibraryItem) => void; onAdd: (item: SoundLibraryItem) => void; onUse: (item: SoundLibraryItem) => void;
  onEditSource: (item: SoundLibraryItem) => void; onUpdate: (item: SoundLibraryItem) => Promise<void>; onCreateCollection: (name: string) => Promise<void>;
}) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [collectionId, setCollectionId] = useState(''); const [duration, setDuration] = useState('ALL');
  const [editing, setEditing] = useState<SoundLibraryItem>(); const [tagText, setTagText] = useState(''); const [collectionName, setCollectionName] = useState(''); const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (editing && !items.some(item => item.id === editing.id)) setEditing(undefined); }, [items, editing]);
  const savedRevision = revisions.find(row => row.id === editing?.revisionId);
  const shown = items.filter(item => {
    const asset = assets.find(row => row.id === item.assetId);
    const text = [item.name, item.attribution.creator, item.attribution.license, ...item.tags].join(' ').toLocaleLowerCase();
    return (filter === 'ARCHIVED' ? item.archived : !item.archived) && text.includes(query.trim().toLocaleLowerCase())
      && (!collectionId || item.collectionIds.includes(collectionId)) && (filter !== 'FAVORITES' || item.favorite)
      && (filter !== 'READY' || asset?.gateStatus === 'APPROVED') && (filter !== 'REVIEW' || asset?.gateStatus !== 'APPROVED')
      && (filter !== 'CREDITS' || !item.attribution.license || !item.attribution.creator)
      && (filter !== 'LOOPS' || revisions.some(revision => revision.id === item.revisionId && revision.snapshot.loop))
      && (duration === 'ALL' || duration === 'HIT' && item.duration <= 2 || duration === 'CUE' && item.duration > 2 && item.duration <= 15 || duration === 'BED' && item.duration > 15);
  });
  async function change(item: SoundLibraryItem) { setSaving(true); setError(''); try { await onUpdate(item); setEditing(undefined); } catch (problem) { setError(problem instanceof Error ? problem.message : 'Could not save these details.'); } finally { setSaving(false); } }
  return <section className="foley-library foley-panel"><header><div><h2>Club sound library</h2><p>{items.filter(item => !item.archived).length} sounds on this device</p></div></header>
    <div className="foley-library-filters"><label>Search sounds<input type="search" aria-label="Search sounds" placeholder="Name, tag, creator or license" value={query} onChange={event => setQuery(event.target.value)} /></label><details className="foley-library-filter-options"><summary>Filter sounds & collections</summary><div className="foley-library-filters"><label>Show<select aria-label="Filter sounds" value={filter} onChange={event => setFilter(event.target.value)}><option value="ALL">All sounds</option><option value="FAVORITES">Favorites</option><option value="READY">Approved for use</option><option value="LOOPS">Saved loops</option><option value="REVIEW">Needs review</option><option value="CREDITS">Credits to finish</option><option value="ARCHIVED">Archived</option></select></label><label>Collection<select aria-label="Sound collection" value={collectionId} onChange={event => setCollectionId(event.target.value)}><option value="">Every collection</option>{collections.map(collection => <option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label><label>Length<select aria-label="Sound length" value={duration} onChange={event => setDuration(event.target.value)}><option value="ALL">Any length</option><option value="HIT">Little hits · up to 2s</option><option value="CUE">Short cues · 2–15s</option><option value="BED">Longer beds · over 15s</option></select></label></div></details></div>
    <details><summary>Make a collection</summary><form className="foley-actions" onSubmit={event => { event.preventDefault(); setSaving(true); void onCreateCollection(collectionName).then(() => setCollectionName('')).catch(problem => setError(String(problem))).finally(() => setSaving(false)); }}><input aria-label="New collection name" placeholder="For example: News show" maxLength={100} value={collectionName} onChange={event => setCollectionName(event.target.value)} /><button disabled={saving || busy || !collectionName.trim()}>Create collection</button></form></details>
    {error && <p role="alert">{error}</p>}
    <div className="foley-sound-list">{shown.map(item => {
      const asset = assets.find(row => row.id === item.assetId); const ready = asset?.gateStatus === 'APPROVED';
      return <article key={item.id} className="foley-sound-card"><header><strong>{item.name}</strong><span className={ready ? 'foley-badge' : 'foley-badge foley-review'}>{ready ? 'Ready' : 'Needs review'}</span></header><SoundWaveform peaks={item.peaks} /><p>{Number.isFinite(item.duration) ? item.duration.toFixed(1) : '?'} sec · {item.attribution.creator || 'Creator not entered'} · {item.attribution.license || 'License not entered'}</p><small>{item.tags.join(' · ')}</small>
        <div className="foley-actions"><button disabled={busy || !ready} onClick={() => onAudition(item)}>Listen</button><button disabled={busy || !ready || item.archived} onClick={() => onAdd(item)}>Add to cue</button></div><details className="foley-sound-more"><summary>More & credits</summary><div className="foley-actions"><button disabled={busy || !ready || item.archived} onClick={() => onUse(item)}>Use sound</button><button disabled={busy || saving} onClick={() => void change({ ...item, favorite: !item.favorite })}>{item.favorite ? 'Unfavorite' : 'Favorite'}</button><button disabled={saving} onClick={() => { setEditing(structuredClone(item)); setTagText(item.tags.join(', ')); setError(''); }}>Details & credits</button>{item.projectId && <button disabled={busy} onClick={() => onEditSource(item)}>Edit layers</button>}</div></details>
      </article>;
    })}</div>{!shown.length && <p className="foley-empty">{items.length ? 'No sounds match these filters.' : 'Bring in a sound, record something, or choose Make from your tools.'}</p>}
    {editing && <section className="foley-detail" aria-label={`Details for ${editing.name}`}><h3>Details & credits</h3>{savedRevision && <details open><summary>Credits saved with this version</summary><pre className="foley-frozen-credits">{[savedRevision.snapshot.credits, ...savedRevision.attribution.map(source => [source.creator, source.license, source.sourceUrl, source.licenseUrl, source.notes].filter(Boolean).join(" · "))].filter(Boolean).join("\n\n") || "No credits were entered for this version."}</pre><p>Changing the library details below does not rewrite this saved arrangement. Edit its layers and save a new version to update the cue.</p></details>}<fieldset disabled={saving || busy}><label>Sound name<input aria-label="Sound name" value={editing.name} maxLength={200} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><SoundCreditFields value={editing.attribution} onChange={attribution => setEditing({ ...editing, attribution })} prefix="Sound" /><label>Tags, separated by commas<input aria-label="Sound tags" value={tagText} onChange={event => setTagText(event.target.value)} /></label><div className="foley-actions">{collections.map(collection => <label key={collection.id}><input type="checkbox" checked={editing.collectionIds.includes(collection.id)} onChange={event => setEditing({ ...editing, collectionIds: event.target.checked ? [...editing.collectionIds, collection.id] : editing.collectionIds.filter(id => id !== collection.id) })} />{collection.name}</label>)}</div><label><input type="checkbox" checked={editing.archived} onChange={event => setEditing({ ...editing, archived: event.target.checked })} />Archive from the library (existing projects keep this sound)</label><div className="foley-actions"><button onClick={() => void change({ ...editing, tags: tagText.split(',').map(tag => tag.trim()).filter(Boolean) })}>Save details</button><button onClick={() => setEditing(undefined)}>Cancel details</button></div></fieldset></section>}
  </section>;
}
