import { copyLocalGroupPiece } from './group-local-piece.js';
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { newId, prosePlainText, type GroupRevision, type Story, type User, type StoryCreationRecipeId } from '@chatter/shared';
import { useStore } from '../store/StoreProvider.js';
import { useGate } from '../gate/GateProvider.js';
import { LoadingStatus } from '../components/LoadingStatus.js';
import { flushSessionCheckpoints } from '../store/session-checkpoint.js';
import type { SessionDirectory } from '../portable/finish-session.js';
import { startGroup, joinGroup, makeGroupPiece, captureGroupRevision, groupEntries, collectGroupEntries, openGroupRevision, adoptGroupWriting, attachGroupMedia } from './group-work.js';
import { encodeGroupArchive, GROUP_ARCHIVE_LIMITS } from './group-archive.js';
import { readGroupFileEntries } from './group-intake.js';
import { readGroupFiles, saveGroupArchive } from './group-drive.js';
import './GroupWork.css';

export const groupEditingPath = (story: Story) => story.creationRecipeId === 'video' ? `/stinger/${story.id}` : story.creationRecipeId === 'podcast' ? `/chatterbox?story=${story.id}` : story.creationRecipeId === 'poster' ? `/blast?story=${story.id}` : `/desk/${story.id}`;
const directoryPicker = () => (window as unknown as { showDirectoryPicker?: (options: { mode: 'read'|'readwrite' }) => Promise<SessionDirectory> }).showDirectoryPicker;
const friendly = (value:string) => value.replace(/[^\p{L}\p{N} _-]/gu,'').trim().replace(/\s+/g,'-').slice(0,64) || 'Group-work';

export function GroupJoin({ me, onChanged }: { me?: User; onChanged:()=>void }) {
 const store=useStore(); const navigate=useNavigate(); const [open,setOpen]=useState(false);const [code,setCode]=useState('');const [title,setTitle]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 return <div className="group-join"><button type="button" className="newsroom-button" disabled={!me} onClick={()=>setOpen(!open)}>Join a story</button>{open&&<form onSubmit={async e=>{e.preventDefault();if(!me||busy)return;setBusy(true);setError('');try{await flushSessionCheckpoints(store);const story=await joinGroup(store,code,me,title);onChanged();setOpen(false);navigate(`/slate/${story.id}`);}catch(err){setError(err instanceof Error?err.message:'Try the story code again.');}finally{setBusy(false);}}}>
 <b>Same story. Your own piece.</b><label>Story code<input autoFocus value={code} onChange={e=>setCode(e.target.value)} placeholder="XXXX-XXXX-XXXX" autoCapitalize="characters" spellCheck={false}/></label><label>Story name <small>(optional)</small><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="The lunch line"/></label><p>The code connects your work when files are collected. It does not send files or fetch the brief.</p>{error&&<p role="alert">{error}</p>}<button className="newsroom-button primary" disabled={busy||!code.trim()}>{busy?'Joining…':'Join story'}</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button>
 </form>}</div>;
}

export function GroupWork({story,me,onChanged,onWritingChanged,onCompare}:{story:Story;me?:User;onChanged:()=>void;onWritingChanged?:(story:Story)=>void;onCompare?:()=>void}) {
 const store=useStore();const {gate}=useGate();const navigate=useNavigate();const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [failed,setFailed]=useState(false);const [revisions,setRevisions]=useState<GroupRevision[]>([]);const [refresh,setRefresh]=useState(0);const [title,setTitle]=useState('');const [recipe,setRecipe]=useState<StoryCreationRecipeId>('article');const [making,setMaking]=useState(false);const [adopting,setAdopting]=useState<GroupRevision>();const [license,setLicense]=useState('');const [creator,setCreator]=useState('');const [source,setSource]=useState('');const [sources,setSources]=useState(false);const [localStories,setLocalStories]=useState<Story[]>([]);const [existing,setExisting]=useState('');const [correctCode,setCorrectCode]=useState('');
 useEffect(()=>{let live=true;store.stories.list().then(rows=>{if(live)setLocalStories(rows.filter(s=>s.id!==story.id&&s.group?.code!==story.group?.code));}).catch(()=>{});return()=>{live=false;};},[store,story.id,story.group?.code,refresh]);
 const files=useRef<HTMLInputElement>(null);const media=useRef<HTMLInputElement>(null);
 useEffect(()=>{let live=true;store.groupRevisions.list().then(rows=>{if(live)setRevisions(rows.filter(r=>r.groupCode===story.group?.code));}).catch(()=>{if(live){setFailed(true);setMessage('The collected pieces could not load. Open this story again.');}});return()=>{live=false;};},[store,story.id,story.group?.code,story.updatedAt,refresh]);
 async function run(label:string,action:()=>Promise<string|void>){if(busy)return;setBusy(label);setMessage('');setFailed(false);try{const result=await action();setMessage(result??'Saved on this computer.');setRefresh(n=>n+1);onChanged();}catch(err){if(err instanceof Error&&err.name==='AbortError')setMessage('Cancelled. Your work is still here.');else{setFailed(true);setMessage(err instanceof Error?err.message:'That did not finish. Please try again.');}}finally{setBusy('');}}
 const writable=!!me&&story.status!=='DONE'&&(!story.ownerId||story.ownerId===me.id||me.role==='ADVISER');
 const canAssemble=!!me&&story.status!=='DONE'&&story.group?.kind!=='piece'&&(story.ownerId===me.id||me.role==='ADVISER');
 async function collect(chosen:File[]){if(!chosen.length)return;await run('Checking and collecting pieces…',async()=>{if(chosen.length>GROUP_ARCHIVE_LIMITS.revisions||chosen.reduce((sum,file)=>sum+file.size,0)>GROUP_ARCHIVE_LIMITS.archiveBytes)throw new Error('Choose fewer files at once; one collection is limited to 512 MB.');const all=[];for(const file of chosen)all.push(...await readGroupFileEntries(file));if(all.some(e=>e.record.groupCode!==story.group?.code))throw new Error('One of these files is for another story. Open it with Open a Story Drive to keep the stories separate.');const result=await collectGroupEntries(store,all);return `${result.added} new version${result.added===1?'':'s'} collected. ${result.already?`${result.already} already here. `:''}The main draft is unchanged.`;});}
 async function saveToDrive(){
  const pick=directoryPicker(); // Start the picker during the click, before packing media.
  await run('Saving group work…',async()=>{const dir=pick?await pick({mode:'readwrite'}):undefined;await flushSessionCheckpoints(store);if(story.group?.kind==='piece')await captureGroupRevision(store,story.id);else for(const member of (await store.stories.list()).filter(s=>s.group?.code===story.group?.code&&s.group?.kind!=='joined'))await captureGroupRevision(store,member.id);const entries=await groupEntries(store,story.group!.code,story.group?.kind==='piece'?story.group.contributionId:undefined);if(!entries.length)throw new Error('Make a piece or collect some work before saving.');const blob=await encodeGroupArchive(entries);const label=`${story.title} — ${story.group?.kind==='piece'?story.group.authorName:'Group collection'}`;if(dir){const path=await saveGroupArchive(dir,blob,label);return `Saved and checked: ${path}. You can now eject the drive.`;}const link=document.createElement('a');const url=URL.createObjectURL(blob);link.href=url;link.download=`${friendly(label)}-${new Date().toISOString().slice(0,10)}-${newId().slice(0,8)}.chatter`;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return 'Download ready. Move the .chatter file to your USB drive; keep its unique name.';});
 }
 if(!story.group)return <section className="group-work group-start"><div><b>Many hands. One story.</b><p>Give your crew a code and collect everyone’s pieces here.</p></div><button className="newsroom-button" disabled={!writable||!!busy} onClick={()=>void run('Starting group story…',async()=>{await startGroup(store,story,me!);return 'Story code ready. Share it with your crew.';})}>Work with a group</button>{message&&<p role={failed?'alert':'status'}>{message}</p>}</section>;
 const parents=new Set(revisions.map(r=>r.parentRevisionId));const heads=revisions.filter(r=>!parents.has(r.id));
 return <section className="group-work" aria-label="Group story work">
 <header><div><span className="newsroom-eyebrow">{story.group.kind==='piece'?'MY PIECE':'GROUP STORY'}</span><h2>{story.group.kind==='piece'?`${story.group.authorName}’s contribution`:'Bring everyone’s work together'}</h2><p>Code connects the story. USB carries the work.</p></div><div className="group-code"><small>Share this story code</small><strong>{story.group.code}</strong><button disabled={!!busy} onClick={()=>void run('Copying code…',async()=>{await navigator.clipboard.writeText(story.group!.code);return 'Code copied. Write it on the board or share it with your crew.';})}>Copy code</button></div></header>
 <div className="group-actions"><button className="newsroom-button primary" disabled={!me||!!busy} onClick={()=>setMaking(!making)}>Make my piece</button><button className="newsroom-button" disabled={!!busy} onClick={()=>files.current?.click()}>Collect files</button>{directoryPicker()&&<button className="newsroom-button" disabled={!!busy} onClick={()=>{const picker=directoryPicker()!;void picker({mode:'read'}).then(readGroupFiles).then(collect).catch(err=>{if(err?.name!=='AbortError'){setFailed(true);setMessage(err instanceof Error?err.message:'Choose a folder again.');}});}}>Collect a folder</button>}<button className="newsroom-button" disabled={!!busy} onClick={()=>void saveToDrive()}>Save {story.group.kind==='piece'?'my piece':'group collection'}</button>{onCompare&&<button className="newsroom-button" onClick={onCompare} disabled={!!busy||!revisions.length}>Compare writing ({heads.length})</button>}<button className="newsroom-button" disabled={!writable||!!busy} onClick={()=>setSources(!sources)}>Add source media</button></div>
 {story.group.kind!=='main'&&<details className="group-correct"><summary>Joined the wrong story?</summary><p>Enter the correct code. Your pieces and attached sources are copied to the correct story; the originals stay here.</p><form className="group-piece-form" onSubmit={e=>{e.preventDefault();void run('Connecting a copy to the correct story…',async()=>{if(!me)return;await flushSessionCheckpoints(store);const target=await joinGroup(store,correctCode,me);if(target.group?.code===story.group?.code)throw new Error('That is already this story’s code.');let copy=target;if(story.group?.kind==='piece')copy=await copyLocalGroupPiece(store,gate,story.id,target,me);else{const local=(await store.stories.list()).filter(s=>s.group?.code===story.group?.code&&s.group?.kind==='piece'&&(s.ownerId===me.id||me.role==='ADVISER'));for(const piece of local)await copyLocalGroupPiece(store,gate,piece.id,target,me);const fresh=await store.stories.get(story.id);if(fresh?.attachedAssetIds?.length||prosePlainText(fresh?.body??{type:'doc'}).trim())await copyLocalGroupPiece(store,gate,story.id,target,me);}onChanged();navigate(`/slate/${copy.id}`);});}}><label>Correct story code<input value={correctCode} onChange={e=>setCorrectCode(e.target.value)} spellCheck={false}/></label><button className="newsroom-button" disabled={!me||!!busy||!correctCode.trim()}>Keep work and correct code</button></form></details>}
 {making&&<form className="group-piece-form" onSubmit={e=>{e.preventDefault();void run('Making your piece…',async()=>{if(!me)return;await flushSessionCheckpoints(store);const piece=await makeGroupPiece(store,story,me,title,recipe);setMaking(false);onChanged();navigate(groupEditingPath(piece));});}}><label>Name your piece<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${me?.penName??'My'}’s perspective`}/></label><label>What are you making?<select value={recipe} onChange={e=>setRecipe(e.target.value as StoryCreationRecipeId)}><option value="article">Writing</option><option value="video">Video</option><option value="podcast">Audio</option><option value="poster">Picture / graphic</option></select></label><button className="newsroom-button primary" disabled={!!busy}>Open my workspace</button></form>}
 {making&&localStories.length>0&&<div className="group-piece-form"><label>Or bring work already on this computer<select value={existing} onChange={e=>setExisting(e.target.value)}><option value="">Choose a story or project</option>{localStories.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><button className="newsroom-button" disabled={!existing||!me||!!busy} onClick={()=>void run('Copying existing work into this group…',async()=>{await flushSessionCheckpoints(store);const copy=await copyLocalGroupPiece(store,gate,existing,story,me!);onChanged();navigate(groupEditingPath(copy));})}>Add a copy</button></div>}
 {sources&&<div className="group-source-form"><p>Add pictures, audio, or video—even things you have not used yet. The actual files travel with your saved piece.</p><label>Creator<input value={creator} onChange={e=>setCreator(e.target.value)}/></label><label>License<select value={license} onChange={e=>setLicense(e.target.value)}><option value="">Not checked yet</option><option value="OWN">Made by our crew</option><option value="CC0">CC0 / public domain</option><option value="CC-BY">CC BY</option><option value="CC-BY-SA">CC BY-SA</option></select></label><label>Source link<input value={source} onChange={e=>setSource(e.target.value)} type="url"/></label><button className="newsroom-button" disabled={!!busy} onClick={()=>media.current?.click()}>Choose media files</button><small>{story.attachedAssetIds?.length??0} attached source files · existing permission checks still apply</small></div>}
 {busy&&<LoadingStatus label={busy} detail="Keep this tab open while the files are checked."/>}{message&&<p className={`newsroom-notice ${failed?'error':''}`} role={failed?'alert':'status'}>{message}</p>}
 {story.group.kind==='joined'&&<p>Your story code is linked. Make your own piece now, or collect the lead’s saved work to continue the main project.</p>}
 {!story.ownerId&&<p>Assembling the final story? Use “I will lead” in this story’s plan first.</p>}
 {heads.length>0&&<details className="group-received"><summary>Collected work · {heads.length} current versions · {revisions.length} saved versions</summary><p>Different edits stay separate. Open a copy to continue any project; choose writing or media to build the main version.</p><div className="group-received-grid">{heads.map(r=><article key={r.id}><small>{r.kind==='main'?'MAIN DRAFT':'CONTRIBUTION'} · {r.authorName} · {r.id.slice(0,6)}</small><h3>{r.title}</h3><p>{prosePlainText(r.body).slice(0,200)||'Media or project files'}</p><div><button disabled={!me||!!busy} onClick={()=>void run('Opening editable copy…',async()=>{const copy=await openGroupRevision(store,gate,r.id,me!);onChanged();navigate(groupEditingPath(copy));})}>Open editable copy</button>{canAssemble&&<button disabled={!!busy} onClick={()=>setAdopting(r)}>Use writing as main</button>}{writable&&<button disabled={!!busy} onClick={()=>void run('Bringing source media…',async()=>{await attachGroupMedia(store,gate,r.id,story.id,me!);return 'Source files added to this story. Open the picture, audio, or video tools to use them.';})}>Bring media here</button>}</div></article>)}</div></details>}
 {adopting&&<div className="group-adopt" role="region" aria-label="Review main writing"><h3>Use “{adopting.title}” as the main writing?</h3><p>Your current main writing is saved as an earlier version first. Other project media and edits stay in their workspaces.</p><pre>{prosePlainText(adopting.body)}</pre><button className="newsroom-button primary" disabled={!!busy} onClick={()=>void run('Saving previous writing and updating main…',async()=>{const updated=await adoptGroupWriting(store,story.id,adopting.id,me!);onWritingChanged?.(updated);setAdopting(undefined);return 'Main writing updated. Both source versions are kept.';})}>Use this writing</button><button disabled={!!busy} onClick={()=>setAdopting(undefined)}>Keep current writing</button></div>}
 <input ref={files} hidden type="file" accept=".chatter,application/zip" multiple onChange={e=>{const selected=Array.from(e.target.files??[]);e.target.value='';void collect(selected);}}/>
 <input ref={media} hidden type="file" accept="image/*,audio/*,video/*" multiple onChange={e=>{const selected=Array.from(e.target.files??[]);e.target.value='';void run('Importing source files…',async()=>{let count=0;for(const file of selected){const kind=file.type.startsWith('image/')?'IMAGE':file.type.startsWith('audio/')?'AUDIO':file.type.startsWith('video/')?'VIDEO':undefined;if(!kind)throw new Error(`Choose an image, audio, or video file: ${file.name}`);if(file.size>256*1024*1024)throw new Error('Choose a source smaller than 256 MB.');const result=await gate.ingest({source:'upload',bytes:new Uint8Array(await file.arrayBuffer()),ownDevice:false,meta:{kind,mime:file.type,origin:'UPLOAD',storyId:story.id,creator:creator.trim()||undefined,license:license||undefined,sourceUrl:source.trim()||undefined}});if(!result.assetId)throw new Error(`${file.name} could not be imported: ${result.reason??result.status}`);await store.credits.create({storyId:story.id,assetId:result.assetId,usedIn:`Source file: ${file.name}`});const fresh=await store.stories.get(story.id);await store.stories.update(story.id,{attachedAssetIds:[...new Set([...(fresh?.attachedAssetIds??[]),result.assetId])]});count++;}return `${count} source file${count===1?'':'s'} attached. They will be included when you save.`;});}}/>
 </section>;
}
