import type { ReilyHelpContext, ReilyHelpTopic } from './reily-help-types.js';

const group = (c: ReilyHelpContext) => Boolean(c.situation?.groupKind);
const master = (c: ReilyHelpContext) => c.situation?.groupKind === 'main';
const drive = (c: ReilyHelpContext) => c.situation?.activeTool === 'story-drive';

/** Instructions match the room controls. No file contents, names, or student text are inspected. */
export const REILY_HANDOFF_HELP: readonly ReilyHelpTopic[] = [
  {
    id: 'handoff.start-group', room: 'slate', title: 'Let friends work on my story',
    keywords: ['code', 'group', 'team', 'join', 'master', 'collaborate'],
    summary: 'The story you started becomes the master. Everyone else can make a separate piece for it.',
    steps: ['Open your story plan. Choose Get story code.', 'Share the whole code with your crew. They choose Join a story and enter it.', 'Save the master to the group’s USB drive. Keep the story folder together for the final handoff.'],
    when: c => Boolean(c.story) && !group(c),
  },
  {
    id: 'handoff.join', room: 'slate', title: 'Join a story with a code',
    keywords: ['join', 'code', 'contribute', 'friend', 'group'],
    summary: 'Joining gives you your own piece. You do not need the USB just to start.',
    steps: ['Choose Join a story and enter the code the story creator shared.', 'Pick Writing, Video, Audio, or Picture / graphic under What will you make?', 'Choose Join and start my piece. When ready, save your piece into the group’s USB folder.'],
    priority: 45, when: c => c.situation?.activeTool === 'group-join',
  },
  {
    id: 'handoff.code-error', room: 'slate', title: 'My story code will not work',
    keywords: ['code', 'invalid', 'join', 'wrong', 'letters'],
    summary: 'Check the code with the creator before starting again.',
    steps: ['Ask the creator to use Copy code, or compare every letter and number on their screen.', 'New codes have two groups of five characters. Older longer Orbit codes still work.', 'Enter the full code in Join a story. Do not invent a replacement: it would link you to a different group.'],
    priority: 95, when: c => c.situation?.activeTool === 'group-join' && c.situation.error === true,
  },
  {
    id: 'handoff.offline-code', room: 'any', title: 'Why can’t my friend see my changes?',
    keywords: ['sync', 'code', 'online', 'friend', 'live', 'internet', 'computer'],
    summary: 'A story code labels work that belongs together. It does not send files between computers.',
    steps: ['Save your latest piece to the group’s USB story folder.', 'The lead opens or connects that folder on their computer.', 'New contributions appear there. Your friend cannot see edits that are still only on your computer.'],
    when: group,
  },
  {
    id: 'handoff.master-connect', room: 'any', title: 'Make the master find everyone’s pieces',
    keywords: ['master', 'folder', 'connect', 'automatic', 'collect', 'contributor'],
    summary: 'The original master stays the master. Connect its folder so Orbit can find nearby contribution files.',
    steps: ['If Connect story folder is available in the master’s group section, choose it and select the story folder on the USB.', 'If your browser has no folder button, open Collect everyone’s work and use Collect files to pick the contributor .chatter files.', 'Allow the browser to access that folder. Keep the master and contributor files inside it.', 'Look under Collected work as pieces arrive. You do not need to save a new master just to collect them.'],
    priority: 65, when: c => master(c) && c.situation?.folderConnected === false,
  },
  {
    id: 'handoff.master-watch', room: 'any', title: 'New pieces are in the folder—what next?',
    keywords: ['master', 'automatic', 'watch', 'refresh', 'contributions'],
    summary: 'While the master’s folder is connected, Orbit checks it for new contributions.',
    steps: ['Keep the USB connected and return to the master in Orbit.', 'Give the folder check a moment, then look under Collected work.', 'Read or open a contribution before deciding what belongs in the final version. Collecting does not replace your main writing.'],
    when: c => master(c) && c.situation?.folderConnected === true && !c.situation.folderError,
  },
  {
    id: 'handoff.folder-error', room: 'any', title: 'My connected folder stopped working',
    keywords: ['USB', 'folder', 'permission', 'disconnected', 'reconnect', 'error'],
    summary: 'Keep your work open and reconnect the same story folder.',
    steps: ['Check that the USB is plugged in and the story folder is still there.', 'Choose Reconnect story folder and allow access. After reopening the browser, you may need to choose Connect story folder instead.', 'If Orbit names a damaged or different-story file, ask the lead to check that file. Do not delete the master or reset Orbit to fix a folder problem.'],
    priority: 100, when: c => c.situation?.folderError === true,
  },
  {
    id: 'handoff.group-error', room: 'any', title: 'Group files did not finish saving or collecting',
    keywords: ['group', 'files', 'collect', 'save', 'error', 'large', 'wrong'],
    summary: 'Keep the story open and use the message beside the group controls to choose the next step.',
    steps: ['For a different-story warning, compare the files’ story codes and select only files for this group. For a size warning, try a smaller batch.', 'For a USB save problem, check the drive connection and permission to save in its folder, then retry the save. Do not clear Orbit’s data.', 'If the message names a damaged file or the retry fails, show the lead or adviser the message and the file. Keep the existing master and contribution copies.'],
    priority: 90, when: c => c.situation?.activeTool === 'group-error' && c.situation.error === true,
  },
  {
    id: 'handoff.save-piece', room: 'any', title: 'Give my contribution to the lead',
    keywords: ['save', 'USB', 'piece', 'contributor', 'handoff', 'drive'],
    summary: 'Save the piece itself so your words and attached source files travel together.',
    steps: ['Open your piece’s story plan and choose Save my piece to USB in the group section.', 'Choose the group’s drive or matching story folder. Orbit uses the code to keep stories separate.', 'Wait for Saved and checked before ejecting. If you get a download instead, move the .chatter file into the named story folder yourself.'],
    priority: 55, when: c => c.situation?.groupKind === 'piece',
  },
  {
    id: 'handoff.save-master', room: 'any', title: 'Save changes I made to the master',
    keywords: ['master', 'save', 'overwrite', 'new', 'edits'],
    summary: 'Save master edits to USB updates the same master file.',
    steps: ['Finish your own edits in the master.', 'Choose Save master edits to USB and wait for the saved message.', 'Leave contributor files beside it in the story folder. They are discovered separately; there is no repacking step after each contribution.'],
    when: master,
  },
  {
    id: 'handoff.wrong-group', room: 'any', title: 'I joined the wrong story',
    keywords: ['wrong', 'code', 'group', 'copy', 'fix', 'joined'],
    summary: 'You can copy your work to the correct group without throwing away the original.',
    steps: ['Open Joined the wrong story? in your piece’s group section.', 'Enter the correct code from the story creator.', 'Choose Keep work and correct code. Check the copied piece, then save it to the correct group’s USB folder.'],
    when: c => c.situation?.groupKind === 'piece' || c.situation?.groupKind === 'joined',
  },
  {
    id: 'handoff.compare', room: 'any', title: 'Read everyone’s writing together',
    keywords: ['compare', 'writing', 'versions', 'four', 'combine', 'perspectives'],
    summary: 'Compare the pieces beside the main draft before choosing words for the final story.',
    steps: ['In Desk, open Collect everyone’s work and choose Compare writing after pieces have been collected.', 'Use Choose writing or Open all pieces to pick what you want to read. Each piece scrolls separately.', 'Highlight a passage and choose Add selected words. Use Show earlier versions to inspect older work; different edits remain separate.'],
    priority: 55, when: c => c.room === 'desk' && (c.situation?.contributionCount ?? 0) > 1,
    action: { label: 'Open Desk', room: 'desk' },
  },
  {
    id: 'handoff.adopt', room: 'any', title: 'Use a whole contribution as the main writing',
    keywords: ['main', 'replace', 'writing', 'adopt', 'master'],
    summary: 'The lead can review a contribution before using it as the main writing.',
    steps: ['In Collected work, choose Use writing as main on the contribution you want.', 'Read the preview. Choose Use this writing to confirm, or Keep current writing to cancel.', 'The previous main writing is kept as a version. This action changes writing; it does not assemble a video or move every media edit into the master.'],
    when: c => master(c) && (c.situation?.contributionCount ?? 0) > 0,
  },
  {
    id: 'handoff.source-media', room: 'any', title: 'Send pictures or sounds with my piece',
    keywords: ['source', 'media', 'attach', 'photo', 'audio', 'video', 'license'],
    summary: 'Attach the actual files, even if you have not used them in your piece yet.',
    steps: ['Choose Add source media in the group section.', 'Fill in Creator, License, and Source link using the real source information. Leave an unknown license as Not checked yet.', 'Choose media files, then save your piece to USB. A web link alone does not pack the sound or picture.'],
    when: c => group(c) && c.situation?.activeTool === 'group-sources',
  },
  {
    id: 'handoff.reuse-media', room: 'any', title: 'Use a teammate’s picture, sound, or video',
    keywords: ['media', 'teammate', 'bring', 'source', 'video', 'audio'],
    summary: 'Collected project files can become editable copies; source media can be brought into your current story.',
    steps: ['Find the teammate’s contribution in Collected work.', 'Choose Bring media here to attach its source files to this story. Open the picture, sound, or video tool to arrange them.', 'To continue their actual project, choose Open editable copy instead. Keep the source credit and permission information.'],
    when: c => group(c) && (c.situation?.contributionCount ?? 0) > 0,
  },
  {
    id: 'handoff.download', room: 'any', title: 'Orbit downloaded a file instead of saving to USB',
    keywords: ['download', 'USB', 'browser', 'folder', 'save', 'Safari'],
    summary: 'A browser download still needs to be put in the right place.',
    steps: ['Open the browser’s Downloads and find the new .chatter file.', 'Move it to your story’s folder on the USB. For group stories, match the code shown in Orbit.', 'Check that the file is there before closing Orbit or ejecting the drive. A download message does not prove it reached the USB.'],
    when: drive,
  },
  {
    id: 'handoff.open-folder', room: 'files', title: 'Open the master with everyone’s contributions',
    keywords: ['open', 'master', 'folder', 'USB', 'contributions'],
    summary: 'Choose the story folder so Orbit has permission to find its contributor files.',
    steps: ['In the Files drawer, choose Open story folder · master + contributions when available.', 'Select the story’s folder containing its master and contributor files—not the whole drive.', 'If only Choose .chatter file is available, open the master that way. Use Collect files for the contributions; opening one file does not give the browser access to its neighbors.'],
    priority: 55, when: drive,
  },
  {
    id: 'handoff.save-story', room: 'files', title: 'Save a story I can keep working on',
    keywords: ['save', 'USB', 'portable', 'chatter', 'project', 'backup'],
    summary: 'A .chatter file keeps editable story work and its linked media together.',
    steps: ['Open Files in the app frame. Under Save the handoff, choose the right Story.', 'Choose Save story, Save to USB, or Prepare story file, depending on this device.', 'Wait for the result. If a Download file or Save to Files step appears, complete it and check the destination.'],
    when: drive,
  },
  {
    id: 'handoff.save-error', room: 'files', title: 'Saving failed—what should I do?',
    keywords: ['save', 'failed', 'error', 'space', 'permission', 'USB'],
    summary: 'Keep Orbit open while you fix the save. Your browser copy and your USB copy are different.',
    steps: ['Read the save message: check the USB connection, free space, and permission to write to the chosen folder.', 'Retry the save to a folder you can use. If available, use the download option and check the downloaded file.', 'Ask the adviser if the school computer refuses folder access. Do not clear browser storage or reset the app to fix a save.'],
    priority: 100, when: c => drive(c) && c.situation?.error === true,
  },
  {
    id: 'handoff.finish-session', room: 'files', title: 'Pack up before leaving this computer',
    keywords: ['finish', 'session', 'leave', 'all', 'ZIP', 'eject'],
    summary: 'Finish session packs the stories on this desk. It does not save future edits.',
    steps: ['Save any open review notes and finish recordings or exports first.', 'In Files, choose Finish session. Follow any Download file or Save to Files step, then check the saved copy.', 'Keep the whole group story folder for handoff. Once saving is complete, close Orbit and eject the USB through the computer’s file app.'],
    when: drive,
  },
  {
    id: 'handoff.media-bin', room: 'files', title: 'Find a file I already made',
    keywords: ['media', 'bin', 'files', 'find', 'export', 'missing', 'download'],
    summary: 'Media Bin shows saved exports and recordings. The Files button opens the story-saving drawer.',
    steps: ['Use Find a file in Media Bin, or choose the Story, Type, and Made in filters.', 'If My files is empty, try All story files. Advisers can use All crew files.', 'Use Download on a file card to take its finished file, or Open its app to keep editing. Save the .chatter story separately when you need editable work on another computer.'],
    when: c => !drive(c),
  },
  {
    id: 'handoff.media-empty', room: 'files', title: 'My export is not in Media Bin',
    keywords: ['empty', 'export', 'missing', 'filters', 'media', 'bin'],
    summary: 'Check the filters and whether the production tool actually finished saving its export.',
    steps: ['Clear Find a file and set Story, Type, and Made in to their Every options. Try All story files.', 'Press Refresh. If there is still no file, return to the app where you made it and complete its save or export.', 'A file marked File missing needs its bytes restored from a saved story copy; changing filters cannot repair it. Ask the adviser before replacing any work.'],
    priority: 60, when: c => !drive(c) && c.situation?.hasContent === false,
  },
  {
    id: 'handoff.crew-start', room: 'crew', title: 'Choose a job and know what to do',
    keywords: ['job', 'assignment', 'role', 'crew', 'start'],
    summary: 'Each assignment has a short brief, three checks, and a room to work in.',
    steps: ['Open Assignment board or Assignments. Filter by Story or Role if needed.', 'Read an open job and choose I will do this.', 'Go to My work, read What done looks like, and use the Open room button for that job.'],
    priority: 50, when: c => c.situation?.projectSelected === false,
  },
  {
    id: 'handoff.crew-stuck', room: 'crew', title: 'Ask a person for help with my job',
    keywords: ['stuck', 'help', 'crew', 'assignment', 'relay'],
    summary: 'Use your relay card to show exactly where you got stuck.',
    steps: ['In My work, open your assignment.', 'Fill in what is finished, where the work is, and what needs to happen next. Name the missing file, answer, permission, or decision.', 'Choose Request help. Tell your lead or adviser too: this local board does not send a message to another computer.'],
    when: c => c.situation?.projectSelected === true,
  },
  {
    id: 'handoff.crew-finish', room: 'crew', title: 'Why is Finish & hand off unavailable?',
    keywords: ['finish', 'disabled', 'gray', 'handoff', 'checklist', 'crew'],
    summary: 'Finishing needs all three job checks and all three parts of the relay card.',
    steps: ['In My work, complete the work described by each check before ticking it.', 'Fill in all three relay-card parts: what is finished, where it is, and what comes next.', 'Choose Finish & hand off. To keep a partial card, choose Save card instead.'],
    priority: 55, when: c => c.situation?.activeTool === 'crew-incomplete',
  },
  {
    id: 'handoff.review-start', room: 'greenlight', title: 'Review a story without guessing',
    keywords: ['review', 'check', 'green', 'light', 'approve'],
    summary: 'Check the actual finished piece, including the pictures, recording, or video.',
    steps: ['Choose a story. If the queue is empty, use Browse pieces in production.', 'Choose Take this review if it has no reviewer. Work through The five checks and open Project notes when you need the sources.', 'Write a Revision note for a specific problem and choose Add note. Only tick checks you have actually completed.'],
    focus: ['greenlight.preview'],
  },
  {
    id: 'handoff.review-notes', room: 'greenlight', title: 'Fix a review note and check it again',
    keywords: ['note', 'revision', 'resolved', 'checks', 'changed'],
    summary: 'Resolve a note after the change is checked, not just after someone promises to fix it.',
    steps: ['Read the Revision note and use Open in the production app to make the change.', 'Return to Green Light and inspect the new result.', 'Mark the note Resolved when it is fixed. If the piece changed after review, repeat the checks that Orbit requires.'],
    focus: ['greenlight.notes'],
  },
  {
    id: 'handoff.review-blocked', room: 'greenlight', title: 'The release board is not clear yet',
    keywords: ['release', 'blocked', 'permission', 'credits', 'checks', 'publish'],
    summary: 'The release board lists what the story still needs before it can go out.',
    steps: ['Look under Credits and release for the checks still open.', 'Finish missing files or credits in their production app. Ask the adviser to handle family permissions or held media.', 'Resolve notes and complete the five checks before Complete crew review. Reily cannot approve permissions or bypass a blocked release.'],
    priority: 65, when: c => c.situation?.projectSelected === true && c.situation.needsApproval === true,
  },
  {
    id: 'handoff.review-publish', room: 'greenlight', title: 'Does completing review put it online?',
    keywords: ['publish', 'online', 'release', 'upload', 'receipt', 'review'],
    summary: 'Crew review and publishing are separate steps.',
    steps: ['Finish the checks and choose Complete crew review.', 'The adviser checks the release board and permissions, then publishes finished files through the school’s usual account.', 'The adviser records the publishing receipt in Orbit. Do not assume a checkmark means the file was uploaded somewhere.'],
    focus: ['greenlight.release'],
  },
  {
    id: 'handoff.reruns-find', room: 'reruns', title: 'Find a finished story or episode',
    keywords: ['archive', 'reruns', 'published', 'search', 'finished', 'episode'],
    summary: 'Reruns shows published editions. Work still in production is listed separately.',
    steps: ['Search by a name, topic, or phrase, or browse Published editions.', 'Try the all filter if an edition seems missing. Recorded words are searchable after a transcript exists.', 'If the story is still in production, open it from Current stories. If it came from another computer, open its saved story file first.'],
  },
  {
    id: 'handoff.reruns-edit', room: 'reruns', title: 'Why can’t I edit the published copy?',
    keywords: ['edit', 'locked', 'published', 'reruns', 'correction', 'followup'],
    summary: 'The published edition preserves what the audience received.',
    steps: ['Use Open replay notes to record what worked and what should change.', 'Use Start the next story for a follow-up rather than rewriting the archived edition.', 'For a mistake already shared publicly, tell the adviser so they can arrange a correction through the school’s publishing account.'],
    when: c => c.situation?.projectSelected === true,
  },
  {
    id: 'handoff.frontdesk-student', room: 'frontdesk', title: 'I need the adviser’s help',
    keywords: ['adviser', 'teacher', 'permission', 'PIN', 'locked', 'front', 'desk'],
    summary: 'Front Desk is the adviser’s workspace. You can keep working on your own story while they handle approvals.',
    steps: ['Tell the adviser which story and which permission or media message stopped you.', 'Use the return button on this screen to continue your story or go to Slate.', 'Use your own badge. Do not borrow an adviser’s PIN to get around a blocked action.'],
    priority: 65, when: c => c.role === 'STUDENT',
  },
  {
    id: 'handoff.frontdesk-adviser', room: 'frontdesk', title: 'Handle the next item at Front Desk',
    keywords: ['adviser', 'queue', 'permissions', 'held', 'media', 'frontdesk'],
    summary: 'The queue points to work that needs an adviser decision.',
    steps: ['Open an item’s action to reach the relevant story or panel. Refresh after a new handoff.', 'In Permissions, use Slip on file only when the real family permission is on file. Use Media checkpoint to inspect held material.', 'Check the result before returning the story to the crew. Permission records and media decisions are not made by Reily.'],
    when: c => c.role === 'ADVISER',
  },
  {
    id: 'handoff.frontdesk-backup', room: 'frontdesk', title: 'Will the newsroom backup carry my media?',
    keywords: ['backup', 'recordings', 'pictures', 'USB', 'PIN', 'records'],
    summary: 'The Front Desk records backup and a portable story package contain different things.',
    steps: ['Records → Back the newsroom up saves records such as stories, permissions, credits, and the log.', 'Use the story’s .chatter package to carry recordings and pictures to another computer.', 'For a group handoff, keep the master and all contributor files together in the story folder.'],
    when: c => c.role === 'ADVISER',
  },
  {
    id: 'handoff.home-start', room: 'home', title: 'Where should I start?',
    keywords: ['start', 'new', 'story', 'lost', 'room', 'assignment'],
    summary: 'Start with the story or job you are working on.',
    steps: ['Use Slate to start a story plan or join a group using its code.', 'Use Crew if a lead has given you an assignment.', 'To continue work from another computer, open Files and choose the saved story or its group story folder.'],
    priority: 25, when: c => c.room === 'home',
    action: { label: 'Open Slate', room: 'slate' },
  },
  {
    id: 'handoff.local-work', room: 'any', title: 'Will my work follow me to another computer?',
    keywords: ['computer', 'badge', 'account', 'cloud', 'save', 'local'],
    summary: 'Your badge identifies you on this desk. It does not upload your projects to an online account.',
    steps: ['Save the story through Files before changing computers.', 'Bring the .chatter file—or the whole group story folder—on the USB.', 'On the next computer, choose your badge and open the saved work. Keep the old copy until you have checked the new one.'],
    when: c => c.room === 'home' || drive(c),
  },
];
